In [70]:
import numpy as np


In [71]:
#use the following code for the questions below
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [72]:
#1
neg_a = np.sum(a < 0)
print(neg_a)
# 4

under_zero = a < 0
print( len(a[under_zero]))
# 4 

4
4


In [73]:
# 2. How many positive numbers are there?

pos_a = np.sum(a > 0)
print(pos_a)

5


In [74]:
# 3. How many even positive numbers are there?

even_a = (a % 2 == 0) & (a > 0)
print(len(a[even_a]))

3


In [75]:
# 4. if you were to add 3 to each data point, how many positive numbers would there be?

((a + 3) > 0).sum()


10

In [76]:
# 5. If you squared each number, what would the new mean and standard deviation be?

square_it = a ** 2
get_mean = square_it.mean()
print(square_it)
# 74.0

get_stdev = square_it.std()
print(get_stdev)
# 144.02

[ 16 100 144 529   4   1   0   0   0  36   9  49]
144.0243035046516


In [77]:
#6
center_func = a - a.mean()

print(center_func)
# [  1.   7.   9.  20.  -5.  -4.  -3.  -3.  -3.  -9.   0. -10.]

# found on the net and wanted to see it
centaur = lambda x: x - x.mean()
data_cent = centaur(a)
print(data_cent)

[  1.   7.   9.  20.  -5.  -4.  -3.  -3.  -3.  -9.   0. -10.]
[  1.   7.   9.  20.  -5.  -4.  -3.  -3.  -3.  -9.   0. -10.]


In [78]:
# 7. Calculate the z-score for each data point. 
# Recall that the z-score is given by: z = (x-u)/o

z_score = (a - a.mean()) / a.std()

print(z_score)



[ 0.12403473  0.86824314  1.11631261  2.48069469 -0.62017367 -0.49613894
 -0.3721042  -0.3721042  -0.3721042  -1.11631261  0.         -1.24034735]


In [85]:
#8A.
a = ([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [86]:
#1.A
sum_of_a = sum(a)
print(sum_of_a)

55


In [87]:
#2.A
min_of_a = min(a)
print(min_of_a)

1


In [88]:
#3.A
max_of_a = max(a)
print(max_of_a)

10


In [90]:
#4.A
mean_of_a = sum(a) / len(a)
print(mean_of_a)

5.5


In [93]:
#5.A
product_of_a = 1
for item in a:
    product_of_a *= item
    
product_of_a


3628800

In [95]:
#6.A
square_of_a = []
for i in a:
    square_of_a.append(i **2)
    
square_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [158]:
#7.A
odds_in_a = [num for num in a if num % 2 == 1]
print(odds_in_a)

[1, 3, 5, 7, 9]


In [183]:
#8.A
evens_in_a = [num for num in a if num % 2 == 0]
print(evens_in_a)

[2, 4, 6, 8, 10]


In [108]:
import numpy as np

In [111]:
b =np.array([
    [3, 4, 5],
    [6, 7, 8]
])

In [116]:
#1.B
sum_of_b = b.sum()
print(sum_of_b)

33


In [119]:
#2.B
min_of_b = b.min()
print(min_of_b)

3


In [120]:
#3.B
max_of_b = b.max()
print(max_of_b)

8


In [122]:
#4.B
product_of_b = b.prod()
print(product_of_b)

20160


In [179]:
#5.B
squares_of_b = b ** 2
print(squares_of_b)

[[ 9 16 25]
 [36 49 64]]


In [180]:
#6.B
odds_in_b = [num for num in a if num % 2 == 1]
print(odds_in_b)

[1, 3, 5, 7, 9]


In [182]:
#7.B
evens_in_b = [num for num in a if num % 2 == 0]
print(evens_in_b)

[2, 4, 6, 8, 10]


In [126]:
#9.B
np.shape(b)

(2, 3)

In [124]:
#10.B
b.transpose()

array([[3, 6],
       [4, 7],
       [5, 8]])

In [127]:
#11.B
np.reshape(b, (6,))

array([3, 4, 5, 6, 7, 8])

In [131]:
#12.B
np.reshape(b,(6,1))

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [132]:
c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [142]:
#1.C
outputs = c.max(), c.min(), c.sum(), c.prod()
type(outputs)
outputs

labels =['max', 'min', 'sum', 'product']

answers = dict(zip(labels, outputs))
print(answers)

{'max': 9, 'min': 1, 'sum': 45, 'product': 362880}


In [145]:
#2.C
c.std()
answers['Std'] = c.std()
print(answers)

{'max': 9, 'min': 1, 'sum': 45, 'product': 362880, 'Std': 2.581988897471611}


In [184]:
#3.C
answers['variance'] = c.var()
print(answers)

{'max': 9, 'min': 1, 'sum': 45, 'product': 362880, 'Std': 2.581988897471611, 'variance': 6.666666666666667}


In [146]:
#4.C
c.shape


(3, 3)

In [149]:
#5.C
c.T


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [151]:
#6.C
np.dot(c,c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [153]:
#7.C
np.sum(c* c.T)

261

In [154]:
#8.C
np.prod(c * c.T)

131681894400

In [156]:
d = np.array ([
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
])

In [159]:
#1.D
ans = {}
ans['Sine'] = np.sin(d)
print(ans)

{'Sine': array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])}


In [160]:
#2.D
ans['Cos'] = np.cos(d)
print(ans)

{'Sine': array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]]), 'Cos': array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])}


In [162]:
#3.D
ans['tan'] = np.tan(d)
print(ans)

{'Sine': array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]]), 'Cos': array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]]), 'tan': array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])}


In [161]:
#4.D
d[(d < 0)]


array([-90, -30, -45, -45])

In [165]:
#5.D
d[(d > 0)]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [166]:
#6.D
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [167]:
#7.D
len(np.unique(d))

11

In [171]:
#8.D
d.shape

(3, 6)

In [177]:
#9.D
new_shape = d.T 
print(new_shape.shape)

(6, 3)


In [175]:
#10.D
d.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])